<?xml version="1.0" ?>
<robot name="stella_wlkata" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="bodyHeight" value="0.253"/>
  <xacro:property name="bodyLength" value="0.44"/>
  <xacro:property name="bodyWidth" value="0.38"/>
  <xacro:property name="bodyMass" value="7.18"/>
  
  <xacro:include filename="$(find stella_description)/urdf/materials.xacro"/>

  <link name="base_footprint"/>

  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link" />
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <link name="base_link">
    <visual>
      <origin xyz="0 0 ${bodyHeight/2}" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://stella_description/meshes/bases/STELLA-N1.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="grey"/>
    </visual>

    <collision>
      <origin xyz="0 0 ${bodyHeight/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${bodyLength} ${bodyWidth} ${bodyHeight}"/>
      </geometry>
    </collision>
    
    <inertial>
      <origin xyz="0 0 ${bodyHeight/2}" rpy="0 0 0"/>
      <mass value="${bodyMass}"/>
      <inertia ixx="${bodyMass*(bodyLength*bodyLength+bodyHeight*bodyHeight)/12}" ixy="0" ixz="0"
               iyy="${bodyMass*(bodyLength*bodyLength+bodyWidth*bodyWidth)/12}" iyz="0"
               izz="${bodyMass*(bodyWidth*bodyWidth+bodyHeight*bodyHeight)/12}" />
    </inertial>
  </link>

  <joint name="imu_joint" type="fixed">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin xyz="0 0 0.071" rpy="0 0 0"/>
  </joint>

  <link name="imu_link"/>

  <joint name="scan_joint" type="fixed">
    <parent link="base_link"/>
    <child link="base_scan"/>
    <origin xyz="${bodyLength/2 - 0.075} 0 0.354" rpy="0 0 ${PI}"/>
  </joint>

  <link name="base_scan" />

  <joint name="camera_joint" type="fixed">
    <parent link="base_link"/>
    <child link="camera_link"/>
    <origin xyz="${bodyLength/2 +0.065} 0 0.45" rpy="0 ${PI/3} 0"/>
  </joint>

  <link name="camera_link" />

  <joint name="wlkata_joint" type="fixed">
    <parent link="base_link"/>
    <child link="wlkata_base_link"/>
    <origin xyz="${bodyLength/2 + 0.02} 0 0.035" rpy="0 0 0"/>
  </joint>

  <link name="wlkata_base_link">
    <inertial>
      <origin
        xyz="0.00072554 2.2065E-05 0.024268"
        rpy="0 0 0" />
      <mass
        value="0.01" />
      <inertia
        ixx="10"
        ixy="0"
        ixz="0"
        iyy="10"
        iyz="0"
        izz="10" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://stella_description/meshes/wlkata_base_link.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.44 0.5 0.56 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://stella_description/meshes/wlkata_base_link.STL" />
      </geometry>
    </collision>
  </link>
  <link
    name="Link1">
    <inertial>
      <origin
        xyz="0.011601 0.022341 0.044136"
        rpy="0 0 0" />
      <mass
        value="0.001" />
      <inertia
        ixx="10"
        ixy="0"
        ixz="0"
        iyy="10"
        iyz="0"
        izz="10" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://stella_description/meshes/Link1.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.83 0.83 0.83 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://stella_description/meshes/Link1.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="joint1"
    type="revolute">
    <origin
      xyz="0 0 0.065406"
      rpy="0 0 0" />
    <parent
      link="wlkata_base_link" />
    <child
      link="Link1" />
    <axis
      xyz="0 0 1" />
    <limit
      lower="-1.7453"
      upper="2.7925"
      effort="200"
      velocity="200" />
  </joint>
  <link
    name="Link2">
    <inertial>
      <origin
        xyz="0.054694 0.0036383 -0.0056108"
        rpy="0 0 0" />
      <mass
        value="0.001" />
      <inertia
        ixx="10"
        ixy="0"
        ixz="0"
        iyy="10"
        iyz="0"
        izz="10" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://stella_description/meshes/Link2.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="1 0.65 0 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://stella_description/meshes/Link2.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="joint2"
    type="revolute">
    <origin
      xyz="0.029687 -0.022 0.061593"
      rpy="3.1402 -1.5708 1.5722" />
    <parent
      link="Link1" />
    <child
      link="Link2" />
    <axis
      xyz="0 0 1" />
    <limit
      lower="-0.5235"
      upper="1.2217"
      effort="200"
      velocity="200" />
  </joint>
  <link
    name="Link3">
    <inertial>
      <origin
        xyz="0.0099997 0.0071403 0.037517"
        rpy="0 0 0" />
      <mass
        value="0.001" />
      <inertia
        ixx="10"
        ixy="0"
        ixz="0"
        iyy="10"
        iyz="0"
        izz="10" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://stella_description/meshes/Link3.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.83 0.83 0.83 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://stella_description/meshes/Link3.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="joint3"
    type="revolute">
    <origin
      xyz="0.108 0 -0.0094471"
      rpy="0 0 0" />
    <parent
      link="Link2" />
    <child
      link="Link3" />
    <axis
      xyz="0 0 1" />
    <limit
      lower="-2.9671"
      upper="1.0472"
      effort="200"
      velocity="200" />
  </joint>
  <link
    name="Link4">
    <inertial>
      <origin
        xyz="-8.0804E-06 0.0043797 0.040569"
        rpy="0 0 0" />
      <mass
        value="0.001" />
      <inertia
        ixx="10"
        ixy="0"
        ixz="0"
        iyy="10"
        iyz="0"
        izz="10" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://stella_description/meshes/Link4.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="1 0.65 0 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://stella_description/meshes/Link4.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="joint4"
    type="revolute">
    <origin
      xyz="0.020001 0.10743 0.031439"
      rpy="-1.5708 0 0" />
    <parent
      link="Link3" />
    <child
      link="Link4" />
    <axis
      xyz="0 0 1" />
    <limit
      lower="-6.1086"
      upper="6.1086"
      effort="200"
      velocity="200" />
  </joint>
  <link
    name="Link5">
    <inertial>
      <origin
        xyz="0.00025302 -0.0020133 0.010352"
        rpy="0 0 0" />
      <mass
        value="0.001" />
      <inertia
        ixx="10"
        ixy="0"
        ixz="0"
        iyy="10"
        iyz="0"
        izz="10" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://stella_description/meshes/Link5.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.44 0.5 0.56 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://stella_description/meshes/Link5.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="joint5"
    type="revolute">
    <origin
      xyz="0 -0.010414 0.06155"
      rpy="1.5708 -1.5708 -3.1416" />
    <parent
      link="Link4" />
    <child
      link="Link5" />
    <axis
      xyz="0 0 -1" />
    <limit
      lower="-3.5779"
      upper="0.6283"
      effort="200"
      velocity="200" />
  </joint>
  <link
    name="Link6">
    <inertial>
      <origin
        xyz="5.5511E-17 5.421E-20 -0.010506"
        rpy="0 0 0" />
      <mass
        value="0.001" />
      <inertia
        ixx="10"
        ixy="0"
        ixz="0"
        iyy="10"
        iyz="0"
        izz="10" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://stella_description/meshes/Link6.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.83 0.83 0.83 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://stella_description/meshes/Link6.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="joint6"
    type="revolute">
    <origin
      xyz="0 -0.01628 0.010525"
      rpy="-1.5708 0 0" />
    <parent
      link="Link5" />
    <child
      link="Link6" />
    <axis
      xyz="0 0 1" />
    <limit
      lower="-6.2832"
      upper="6.2832"
      effort="200"
      velocity="200" />
  </joint>  

</robot>
